pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: squash
        strict: true
