queue_rules:
  - name: default
    conditions:
      - status-success=build

pull_request_rules:
  - name: merge approved changes
    conditions:
      - base=dev
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
  - name: automerge dependencies
    conditions:
      - author~=(pyup-bot|dependabot)
      - -files~=^(!?.github/workflows/)
    actions:
      queue:
        name: default


