apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: ghcr.io/pennydreadfulmtg/gatherling/app
    context: .
    docker:
      dockerfile: Dockerfile
  - image: ghcr.io/pennydreadfulmtg/gatherling/mysql
    context: helm/mysql-test
    docker:
      dockerfile: mysql.Dockerfile
  local:
    push: false
    useBuildkit: true
    concurrency: 0
profiles:
- name: dev
  activation:
  - command: dev
  manifests:
    helm:
      flags:
        install:
        - --debug
        upgrade:
        - --debug
      releases:
      - name: gatherling
        chartPath: helm/gatherling
        namespace: default
        setValues:
          environment.type: dev
          app.image: ghcr.io/pennydreadfulmtg/gatherling/app
          app.replicaCount: 1
          mysqlDev.image: ghcr.io/pennydreadfulmtg/gatherling/mysql
  deploy:
    helm: {}
# For a production deployment, refer to the README.md file in the helm/gatherling folder.