{{- if eq .Values.environment.type "dev" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gatherling.fullname.mysql" . }}
  labels:
    gatherling.com/role: mysql
    {{- include "gatherling.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "gatherling.fullname.mysql" . }}
  replicas: 1
  selector:
    matchLabels:
      gatherling.com/role: mysql
      {{- include "gatherling.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        gatherling.com/role: mysql
        {{- include "gatherling.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: mysql
        image: {{ .Values.mysqlDev.image | quote }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        startupProbe:
          tcpSocket:
            port: 3306
          failureThreshold: 30
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 3306
          failureThreshold: 5
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gatherling.fullname" . }}-pvc-deleter-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "delete", "deletecollection"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gatherling.fullname" . }}-pvc-deleter-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gatherling.fullname" . }}-pvc-deleter-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gatherling.fullname" . }}-pvc-deleter-role
subjects:
- kind: ServiceAccount
  name: {{ include "gatherling.fullname" . }}-pvc-deleter-sa
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gatherling.fullname" . }}-pvc-deleter-job
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: post-delete-job
        image: "bitnami/kubectl"
        command: ["bash", "-c", "kubectl delete statefulset/{{ include "gatherling.fullname.mysql" . }} pvc/data-{{ include "gatherling.fullname.mysql" . }}-0 || true"]
      serviceAccountName: {{ include "gatherling.fullname" . }}-pvc-deleter-sa
      securityContext:
        runAsUser: 0
{{- end -}}