apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gatherling.fullname" . }}
  labels:
    gatherling.com/role: app
    {{- include "gatherling.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      gatherling.com/role: app
      {{- include "gatherling.selectorLabels" . | nindent 6 }}