apiVersion: v1
kind: Service
metadata:
  name: {{ include "gatherling.fullname" . }}
  labels:
    gatherling.com/role: app
    {{- include "gatherling.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.environment.type "dev" }}
  type: NodePort
  {{- end }}
  ports:
  - port: 80
    targetPort: http
    name: http
    {{- if eq .Values.environment.type "dev" }}
    nodePort: 30080
    {{- end }}
  selector:
    gatherling.com/role: app
    {{- include "gatherling.selectorLabels" . | nindent 4 }}